### ISSUE TITLE
Switching databases

### ISSUE THREAD

**Issue by EricCroyle** [ttessarolo/useDexie#1]
Is it possible to switch the current database used by `useDexie()`? I see the line:

https://github.com/ttessarolo/useDexie/blob/0386ac69920550a3c0fd9ccdb99db77a39268ad6/index.js#L240

Would simply commenting this line allow for such a case or is there another way? Or am I missing something?

Thanks!

**Comment by ttessarolo** [comment]
No, it is not possible. As a design choice useDexie supports one database at a time. This is because once the database is set with useDexie("db_name") the database is shared via a module variable for all other hooks. This facilitates the use of hooks by preventing you from having to specify the database name each time. It is still possible to share data instead of on multiple databases on multiple tables of a single database.
